# Generated by Django 5.0.4 on 2024-04-22 16:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicCurrencyValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(choices=[(52148, 'Доллар'), (52170, 'Eвро'), (52146, 'Фунт'), (52246, 'Японская йена'), (52158, 'Турецкая лира'), (52238, 'Индийская рупия'), (52207, 'Китайский юань')], default='52148', unique=True, verbose_name='Название валюты')),
                ('date', models.DateField(default=datetime.date(2024, 4, 22), verbose_name='Дата')),
                ('course', models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Основные значения валюты',
                'verbose_name_plural': 'Основные значения валют',
                'ordering': ['title', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(choices=[(52148, 'Доллар'), (52170, 'Eвро'), (52146, 'Фунт'), (52246, 'Японская йена'), (52158, 'Турецкая лира'), (52238, 'Индийская рупия'), (52207, 'Китайский юань')], default='52148', verbose_name='Название валюты')),
                ('date', models.DateField(default=datetime.date(2024, 4, 22), verbose_name='Дата')),
                ('course', models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='Курс')),
                ('base_value', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_value', to='app.basiccurrencyvalues', verbose_name='Базовое значение')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['title', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название страны')),
                ('number', models.IntegerField(default=840, verbose_name='Номер')),
                ('currency', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='app.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
    ]
